package NLGService.test;

import org.junit.Test;

import com.hp.hpl.jena.ontology.OntModel;

import NLGService.WYSIWYM.ontology.SesameReader;
import junit.framework.TestCase;


public class SesameReaderTest extends TestCase{
	private static SesameReader sesame;
	public static final String RESOURCE_ID = "http://www.policygrid.org/project.owl#aadb9597-6392-42e0-9815-489cbe80cd19";
	
	@Override
	protected void setUp() throws Exception {
		super.setUp();
		sesame = new SesameReader(false);
	}
	
	@Test
	public void testJenaModel() {
		OntModel jenaModel = sesame.getJenaModel(RESOURCE_ID);
		assertNotNull("The Jena model generated by the sesame reader is null", jenaModel);
	}
	
	@Override
	protected void tearDown() throws Exception {
		super.tearDown();
		sesame = null;
	}
}
